#!/usr/bin/env ruby
require 'rubygems'
require 'active_support/inflector'

unless action = ARGV[0]
  puts 'you must provide an argument to destroy'
  exit
end

unless File.exist?(destroyer_file = File.join(File.dirname(__FILE__),'destroyers',"#{action}.rb"))
  puts "the action #{action} is not a valid destroy option"
  exit
end

require destroyer_file

begin
  destroyer = TestSweet.const_get("#{Inflector.camelize(action)}Destroyer").new(*ARGV[1..-1])
  destroyer.destroy
rescue ArgumentError => e
  puts e.message
end