#!/usr/bin/env ruby
require 'rubygems'
require 'active_support/inflector'

unless action = ARGV[0]
  puts 'you must provide an argument to generate'
  exit
end

unless File.exist?(generator_file = File.join(File.dirname(__FILE__),'generators',"#{action}.rb"))
  puts "the action #{action} is not a valid generate option"
  exit
end

require generator_file

begin
  generator = TestSweet.const_get("#{Inflector.camelize(action)}Generator").new(*ARGV[1..-1])
  generator.generate
rescue ArgumentError => e
  puts e.message
end